# Generated by Django 4.1.1 on 2022-10-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pic",
            field=models.FileField(default="sad.jpg", upload_to="profile"),
        ),
    ]
